"""sync models.py

Revision ID: 65ba8a38a7a7
Revises: 1f2a3b4c5d66
Create Date: 2025-08-18 18:23:04.253080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ba8a38a7a7'
down_revision: Union[str, Sequence[str], None] = '1f2a3b4c5d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('llm_model', sa.String(), nullable=True))
    op.add_column('interactions', sa.Column('llm_tokens_used', sa.Integer(), nullable=True))
    op.add_column('interactions', sa.Column('llm_cost', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('llm_response_time', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('review_llm_model', sa.String(), nullable=True))
    op.add_column('interactions', sa.Column('review_llm_tokens_used', sa.Integer(), nullable=True))
    op.add_column('interactions', sa.Column('review_llm_cost', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('review_llm_response_time', sa.Float(), nullable=True))
    op.drop_column('interactions', 'user_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('user_rating', sa.INTEGER(), nullable=True))
    op.drop_column('interactions', 'review_llm_response_time')
    op.drop_column('interactions', 'review_llm_cost')
    op.drop_column('interactions', 'review_llm_tokens_used')
    op.drop_column('interactions', 'review_llm_model')
    op.drop_column('interactions', 'llm_response_time')
    op.drop_column('interactions', 'llm_cost')
    op.drop_column('interactions', 'llm_tokens_used')
    op.drop_column('interactions', 'llm_model')
    # ### end Alembic commands ###
