"""add response column to interactions

Revision ID: 8ce751882688
Revises: 
Create Date: 2025-08-18 10:24:08.827954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce751882688'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default to satisfy NOT NULL constraint for existing rows
    op.add_column('interactions', sa.Column('response', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('user_rating', sa.INTEGER(), nullable=True))
    op.drop_column('interactions', 'response')
    # ### end Alembic commands ###
